# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Gleb Grishakov
title: Ruby Developer
email: glebson1988@yandex.ru
website: www.glebkaif.ru

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  glebson1988
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: glebkaif
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Habr
  icon: fas fa-globe
  url: https://career.habr.com/glebson1988
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Gleb and I'm a Ruby developer. I have an experience making web apps. I have worked at a number of companies gaining teamwork skills.
  I am most skilled in: <mark>Ruby</mark> and <mark>Ruby on Rails</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Billing
        #link: github.com/sproogen
        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          December 2021 - present.
        description: | # this will include new lines to allow paragraphs
          A service that implements everything related the calculating the cost of services, invoicing, working with related docs, etc.

          Role: <mark>Fullstack Developer</mark>.

          Responsibilities: New features.

          Environment: <mark>Ruby, Rails, RSpec, MySQL, Docker, Slack API, Sidekiq, Redis</mark>.
      - layout: top-middle
        title: Team
        quote: >
          Aug 2021 - Dec 2021
        description: |
          Web app that is used to create CV and store information about employees, up-to-date information about company and projects.

          Role: <mark>Fullstack Developer</mark>.

          Responsibilities: New features, code review, deploy.

          Environment: <mark>Ruby, Rails, RSpec, PostgreSQL, Heroku</mark>.

      - layout: top-middle
        title: Wriite
        quote: >
          Aug 2021 - Oct 2021
        description: |
          Guided writing and practices that help to reduce anxiety, relieve depression and overcome the effects of lockdown.

          Role: <mark>Team lead</mark>.

          Responsibilities: Team leading, code review.

          Environment: <mark>Ruby, Rails, RSpec, React, Heroku</mark>.

      - layout: top-middle
        title: Melobeem
        quote: >
          Jan 2021 - Aug 2021
        description: |
          Kids competition app. You vote for cute kids, buy votes, spins etc. And at the end of monthly competition take your prize!

          Role: <mark>Backend developer</mark>.

          Responsibilities: Rails API, dockerising app for development, adding Github CI. Also working with AWS (ECR, EC2, RDS etc). Adding Stripe payment system. Sidekiq scheduled jobs.

          Environment: <mark>Ruby, Rails, RSpec, Redis, Amazon: EC2, ECS, RDS; Docker, GitHub Actions, Facebook API, Stripe, Sidekiq</mark>.

      - layout: top-middle
        title: Viviosites
        quote: >
          Jun 2021 - Jul 2021
        description: |
          Dental website CMS.

          Role: <mark>Fullstack developer</mark>.

          Responsibilities: Adding new themes for the template engine, written on RoR 3rd version!

          Environment: <mark>Ruby, Rails, Docker, jQuery</mark>.

      - layout: top-middle
        title: Helpthemove
        quote: >
          Nov 2020 - Jun 2021
        description: |
          Portal for landlords facilitating the transfer of meter readings.

          Role: <mark>Fullstack developer</mark>.

          Responsibilities: New features, also integration new web tool for report generation.

          Environment: <mark>Ruby, Rails, Bootstrap, jQuery, Sidekiq, Postgres, dry-struct, dry-monads, Heroku</mark>.

      - layout: top-middle
        title: Floe Optometry
        quote: >
          Jul 2020 - Oct 2020
        description: |
          App for the optometry practice. It provides office management tools and sales integration with the optics distributor.

          Role: <mark>Fullstack developer</mark>.

          Responsibilities: New features and fixing bugs.

          Environment: <mark>Ruby, Rails, Sidekiq, Postgres, Gitlab, Docker, HIPAA Compliance</mark>.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
